language: php

php:
    - 7.1
    - 7.2

install:
    - composer install
    - composer create-project nette/coding-standard:@dev temp/nette-coding-standard

script:
    - temp/nette-coding-standard/ecs check src examples --config temp/nette-coding-standard/coding-standard-php71.neon
    - composer test

notifications:
    email: false

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
