language: php

php:
    - 7.1
    - 7.2

matrix:
    allow_failures:
        - php: 7.2
    fast_finish: true

install:
    - composer install
    - composer create-project nette/coding-standard:@dev temp/nette-coding-standard

script:
    - temp/nette-coding-standard/ecs check src examples --config temp/nette-coding-standard/coding-standard-php71.neon
    - composer test
    # to try out PR 16
    - temp/nette-coding-standard/ecs check pull-request-16 --config pull-request-16.neon


notifications:
    email: false

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
