language: php

php:
    - 7.1
    - 7.2

matrix:
    include:
        - php: 7.1
          env: COMPOSER_PROJECT=true

install:
    - composer install
    - if [[ $COMPOSER_PROJECT != "" ]]; then composer create-project galek/coding-standard:dev-master temp/coding-standard; fi

script:
    - composer test
    - if [[ $COMPOSER_PROJECT != "" ]]; then temp/coding-standard/ecs check src examples --config temp/coding-standard/coding-standard-php71.yml; fi

notifications:
    email: false

sudo: false
