language: php

php:
    - 7.1

install:
    - composer install
    - composer create-project nette/coding-standard temp/nette-coding-standard

script:
    - temp/nette-coding-standard/ecs check src examples --config temp/nette-coding-standard/coding-standard-php71.neon

notifications:
    email: false
