#!/usr/bin/env php
<?php declare(strict_types=1);

use Symfony\Component\DependencyInjection\Container;
use Symplify\EasyCodingStandard\Console\Application;
//use Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory;

require __DIR__ . '/vendor/symplify/easy-coding-standard/bin/autoload.php';

// performance boost
gc_disable();

try {
    /** @var Container $container */
    $container = require __DIR__ . '/vendor/symplify/easy-coding-standard/bin/container.php';

    /** @var Application $application */
    $application = $container->get(Application::class);

    exit($application->run());
} catch (Throwable $throwable) {
	(new \Symplify\PackageBuilder\Console\ThrowableRenderer())->render($throwable);
    /*$symfonyStyle = SymfonyStyleFactory::create();
    $symfonyStyle->error($throwable->getMessage());*/
    exit(1);
}
